# Generated by Django 4.1.1 on 2022-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="skill", to="api.skilltag"
            ),
        ),
    ]
