# Generated by Django 4.1.1 on 2022-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_application_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="jobId",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
