# Generated by Django 4.1.1 on 2022-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_application_jobid"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
