# Generated by Django 4.1.1 on 2022-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_application_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="selected",
            field=models.CharField(default="False", max_length=4),
        ),
    ]
